#!/bin/bash
#
# Regular user PS1 config

#Including colors
source $MB_DIR/colors
alias GIT='__git_ps1 %s'

# Placeholders
TIMESTAMP=$LIGHT_GRAY
USER=$GREEN
AT=$YELLOW
HOST=$BLUE
DIR=$YELLOW
GIT_CLR=$LIGHT_YELLOW
TXT=$WHITE
SEP=$RED

setup_ps1() {
  export PS1="\n $TIMESTAMP[\t] $USER\u$AT@$HOST\H $DIR(\w): $GIT_CLR[$(GIT)]\n    $SEP\$$TXT "
}