#!/bin/bash
#
# Hard coded DB of quotes.
# Yes, I know I could've done this in a "better way"

quotes[0]="Be the change you wish to see in the world."
authors[0]="Mahatma Ghandi"

quotes[1]="A man who dares to waste one hour of time has not discovered the value of life."
authors[1]="Charles Darwin"

quotes[2]="Never be bullied into silence. Never allow yourself to be made a victim. Accept no one's definition of your life. Define yourself."
authors[2]="Harvey Fierstein"

quotes[3]="Always forgive your enemies. Nothing annoys them so much."
authors[3]="Oscar Wilde"

quotes[4]="Life is what happens to you while you're busy making other plans."
authors[4]="Allen Saunders"

quotes[5]="Whenever you find yourself in the side of the majority, it is time to pause and reflect."
authors[5]="Mark Twain"

quotes[6]="Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning."
authors[6]="Rich Cook"

quotes[7]="One of my most productive days was throwing away 1000 lines of code."
authors[7]="Ken Thompson"

quotes[8]="There's no reality except the one contained within us. That's why so many people live an unreal life. They take images outside them for reality and never allow the world within them to assert itself."
authors[8]="Hermann Hesse"

quotes[9]="Eternity is a mere moment, just long enough for a joke."
authors[9]="Hermann Hesse"

quotes[10]="No man has ever been entirely and completely himself. Yet each one strives to become that — one in an awkward, the other in a more intelligent way, each as best he can."
authors[10]="Hermann Hesse"

quotes[11]="I do not consider myself less ignorant than most people. I have been and still am a seeker, but I have ceased to question stars and books; I have begun to listen to the teachings my blood whispers to me."
authors[11]="Hermann Hesse"

quotes[12]="Happiness is a how, not a what. A talent, not an object."
authors[12]="Hermann Hesse"

quotes[13]="Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless."
authors[13]="Jamie Paolinetti"

quotes[14]="Believe you can and you're half way there."
authors[14]="Theodore Rosevelt"

quotes[15]="If you're not failing every now and again, it's a sign you're not doing anything very innovative"
authors[15]="Woody Allen"

quotes[16]="He not busy being born is busy dying."
authors[16]="Bob Dylan"

quotes[17]="The tongue like a sharp knife... Kills without drawing blood."
authors[17]="Gautama Buddha"

quotes[18]="There are only two mistakes one can make along the road to truth; not going all the way, and not starting."
authors[18]="Gautama Buddha"

quotes[19]="We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves."
authors[19]="Gautama Buddha"

quotes[20]="I never see what has been done; I only see what remains to be done."
authors[20]="Gautama Buddha"

quotes[21]="The mind is everything. What you think you become."
authors[21]="Gautama Buddha"

quotes[22]="It is better to conquer yourself than to win a thousand battles. Then the victory is yours. It cannot be taken from you, not by angels or by demons, heaven or hell."
authors[22]="Gautama Buddha"

quotes[23]="In the end these things matter most: How well did you love? How fully did you live? How deeply did you let go?"
authors[23]="Gautama Buddha"

quotes[24]="The whole secret of existence is to have no fear. Never fear what will become of you, depend on no one. Only the moment you reject all help are you freed."
authors[24]="Gautama Buddha"

quotes[25]="Meditate. Live purely. Be quiet. Do your work with mastery. Like the moon, come out from behind the clouds! Shine."
authors[25]="Gautama Buddha"

quotes[26]="Nothing can harm you as much as your own thoughts unguarded."
authors[26]="Gautama Buddha"

quotes[27]="Nothing is forever except change."
authors[27]="Gautama Buddha"

quotes[28]="With our thoughts we make the world."
authors[28]="Gautama Buddha"

quotes[29]="In the sky, there is no distinction of east and west; people create distinctions out of their own minds and then believe them to be true."
authors[29]="Gautama Buddha"

quotes[30]="Better than a thousand hollow words is one word that brings peace."
authors[30]="Gautama Buddha"

quotes[31]="Happiness comes when your work and words are of benefit to others."
authors[31]="Gautama Buddha"

quotes[32]="Those who have failed to work toward the truth have missed the purpose of living."
authors[32]="Gautama Buddha"

quotes[33]="It's not denial. I'm just selective about the reality I accept."
authors[33]="Bill Watterson"

quotes[34]="Sometimes when I'm talking, my words can't keep up with my thoughts. I wonder why we think faster than we speak. Probably so we can think twice."
authors[34]="Bill Watterson"

quotes[35]="You know, Hobbes, some days even my lucky rocket ship underpants don't help."
authors[35]="Bill Watterson"

quotes[36]="All you need is love."
authors[36]="John Lennon"

quotes[37]="I am the walrus."
authors[37]="John Lennon"

quotes[38]="Time you enjoy wasting, was not wasted."
authors[38]="John Lennon"

quotes[39]="Reality leaves a lot to the imagination."
authors[39]="John Lennon"

quotes[40]="Count your age by friends, not years. Count your life by smiles, not tears."
authors[40]="John Lennon"

quotes[41]="I believe in everything until it's disproved. So I believe in fairies, the myths, dragons. It all exists, even if it's in your mind. Who's to say that dreams and nightmares aren't as real as the here and now?"
authors[41]="John Lennon"

quotes[42]="When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down ‘happy’. They told me I didn’t understand the assignment, and I told them they didn’t understand life."
authors[42]="John Lennon"

quotes[43]="Honesty may be the best policy, but it’s important to remember that apparently, by elimination, dishonesty is the second-best policy."
authors[43]="George Carlin"

quotes[44]="The reason I talk to myself is because I’m the only one whose answers I accept."
authors[44]="George Carlin"

quotes[45]="The very existence of flamethrowers proves that sometime, somewhere, someone said to themselves, “You know, I want to set those people over there on fire, but I’m just not close enough to get the job done.”"
authors[45]="George Carlin"

quotes[46]="Just when I discovered the meaning of life, they changed it."
authors[46]="George Carlin"

quotes[47]="Education is the most powerful weapon which you can use to change the world."
authors[47]="Nelson Mandela"

quotes[48]="When a man is denied the right to live the life he believes in, he has no choice but to become an outlaw."
authors[48]="Nelson Mandela"

quotes[49]="It always seems impossible until it's done."
authors[49]="Nelson Mandela"

quotes[50]="I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear."
authors[50]="Nelson Mandela"

quotes[51]="No one is born hating another person because of the color of his skin, or his background, or his religion. People must learn to hate, and if they can learn to hate, they can be taught to love, for love comes more naturally to the human heart than its opposite."
authors[51]="Nelson Mandela"

quotes[52]="Resentment is like drinking poison and then hoping it will kill your enemies."
authors[52]="Nelson Mandela"

quotes[53]="For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others."
authors[53]="Nelson Mandela"

quotes[54]="The greatest glory in living lies not in never falling, but in rising every time we fall."
authors[54]="Nelson Mandela"

quotes[55]="Lead from the back — and let others believe they are in front."
authors[55]="Nelson Mandela"

quotes[56]="Do not judge me by my successes, judge me by how many times I fell down and got back up again."
authors[56]="Nelson Mandela"

quotes[57]="Where you stand depends on where you sit."
authors[57]="Nelson Mandela"

quotes[58]="I, not events, have the power to make me happy or unhappy today. I can choose which it shall be. Yesterday is dead, tomorrow hasn't arrived yet. I have just one day, today, and I'm going to be happy in it."
authors[58]="Groucho Marx"

quotes[59]="The secret of life is honesty and fair dealing. If you can fake that, you've got it made."
authors[59]="Groucho Marx"

quotes[60]="A black cat crossing your path signifies that the animal is going somewhere."
authors[60]="Groucho Marx"

quotes[61]="Those are my principles, and if you don't like them... well, I have others."
authors[61]="Groucho Marx"

quotes[62]="I find television very educational. Every time someone switches it on I go into another room and read a good book."
authors[62]="Groucho Marx"

quoteLen=${#quotes[@]} # Exporting number of quotes

#Debugging purposes
#COL=50
#for (( i=0; i<$quoteLen; i++ ));
#do
#  echo ${quotes[$i]}
#  printf "%*s %s %s %s" $COL ${authors[$i]} $i
#  printf "\n\n"
#done