#!/bin/zsh

alias vw="view"
alias v="nvim"
alias vv="vim"
alias g="git"
alias at="atom"
alias zx="zeus" # used to be z but thats for autojumping
alias gh="git.browse" # see bin/git.browse

# postgres on OS X
alias pg.server="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log"

alias ta="tmux attach"
alias sr="screen -r"

alias irssi='TERM=screen-256color irssi'

# vim-like exit
alias :q="exit"
alias :qa="_qa"

# Creating compacted cd ..
alias ..="cdl .."
alias ..2="cdl ../.."
alias ..3="cdl ../../.."
alias ..4="cdl ../../../.."
alias ..5="cdl ../../../../.."

# r for rails
if which rails &> /dev/null;
    then alias r="rails"
fi

if which guard &> /dev/null;
    then alias beg="bundle exec guard"
fi

# prolog alias
if which sicstus &> /dev/null;
    then alias prolog="rlwrap sicstus"
fi

# Group ls by name, type & extension
if which gls &> /dev/null;
then
  alias ll="gls -lFX --color"
else
  alias ll="ls -lFX"
fi

gcl() {
    if which git &> /dev/null; then
      git clone $@ && cd $( echo $@ | awk -F/ '{ print $NF }' | cut -d. -f1 )
    fi
}

sb () {
    if which subl &> /dev/null;
        then subl $@
    elif which subl3 > /dev/null;
        then subl3 $@
    else
        subl $@ 2>&1 > /dev/null &
    fi
}

# Creating mkcd: mkdir and cd
mkcd () {
    mkdir -p "$@";
    cd "$@"
}

# Creating cdl: cd and ls
cdl () {
    if [ "$#" -eq "0" ];
        then
            cd "$HOME";
        else
            cd "$@";
    fi

    ls;
}

# Copying text to clipboard
copy() {
    if which xclip &> /dev/null; then
        xclip -selection clipboard < $@
    elif which pbcopy &> /dev/null; then
        if [ -f $@ ]; then
            cat $@ | pbcopy
        else
            echo $@ | pbcopy
        fi
    fi
}

# Reloading rc file
reload() {
    eval source $( echo $SHELL | awk -F/ '{ print "$HOME/."$NF"rc" }' )
}

alias rl="reload"
