#!/bin/zsh

# v command for vim
if which vim &> /dev/null
    then alias v="vim"
fi

alias v.="v ."
alias vw="view"

#v() {
#    if which vim &> /dev/null;
#        then vim $@
#    fi
#}


# r command for rails
if which rails &> /dev/null;
    then alias r="rails"
fi

# g command for git
if which git &> /dev/null;
    then alias g="git"
fi

gcl() {
    if which git &> /dev/null;
    then
        git clone $@ | cd $( echo $@ | awk -F/ '{ print $NF }' | cut -d. -f1)
    fi
}


# Creating sb command for Sublime Text
sb () {
    if which subl &> /dev/null;
        then subl $@
    elif which subl3 > /dev/null;
        then subl3 $@
    else
        subl $@ 2>&1 > /dev/null &
    fi
}

# atom alias
alias at="atom"

# Removing TeamSpeak 3 Client Polution
ts3 () {
    nohup ts3client 2>&1 > /dev/null &
    exit 1
}

# Creating mkcd: mkdir and cd
mkcd () {
    mkdir -p "$@";
    cd "$@"
}

# Creating cdl: cd and ls
cdl () {
    if [ "$#" -eq "0" ];
        then
            cd "$HOME";
        else
            cd "$@";
    fi

    ls;
}

# Creating compacted cd ..
alias ..="cdl .."
alias ..2="cdl ../.."
alias ..3="cdl ../../.."
alias ..4="cdl ../../../.."
alias ..5="cdl ../../../../.."

catl () {
    cat $@ | less
}

# Reloading rc file
reload() {
    eval source $( echo $SHELL | awk -F/ '{ print "$HOME/."$NF"rc" }' )
}

alias rl="reload"

# vim-like exit
alias :q="exit"

# Resuming screen
alias sr="screen -r"

# zeus alias
alias z="zeus"

# valgrind alias
alias valleak="valgrind --tool=memcheck --leak-check=yes"
alias valleak-line="valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all"

# prolog alias
alias prolog="rlwrap sicstus"

