#!/bin/sh
# git clone a repo and cd to it

git-clone-cd() {
  if which hub &> /dev/null ; then
    local git="hub"
  else
    local git="git"
  fi

  $git clone $@ && cd $( echo $@ | awk -F/ '{ print $NF }' | cut -d. -f1 )
}

alias gcl="git-clone-cd"
