cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'telemachus/homebrew-desc'

brew 'arp-scan'
brew 'chruby'
brew 'cowsay'
brew 'ctags'
brew 'curl'
brew 'diff-so-fancy'
brew 'direnv'
brew 'gawk'
brew 'git'
brew 'imagemagick'
brew 'mpv'
brew 'neovim/neovim/neovim'
brew 'openssl'
brew 'postgresql'
brew 'ripgrep'
brew 'reattach-to-user-namespace' --with-wrap-pbcopy-and-pbpaste
brew 'spark'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

cask 'google-chrome'
cask 'pgweb'
cask 'slack'
cask 'spotify'
cask 'transmission'
cask 'vagrant'
cask 'virtualbox'
