cask_args appdir: '/Applications'
tap 'caskroom/cask'
tap 'telemachus/homebrew-desc'

brew 'ctags'
brew 'curl'
brew 'gawk'
brew 'git'
brew 'imagemagick'
brew 'mpv'
brew 'neovim/neovim/neovim'
brew 'openssl'
brew 'postgresql'
brew 'rbenv'
brew 'spark'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask 'transmission'
