#!/usr/bin/env sh
#
# run this everytime you build neovim
# see https://github.com/neovim/neovim/issues/2048#issuecomment-78045837
#

source $DOTFILES/functions/helpers.zsh

infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
tic $TERM.ti
rm $TERM.ti

_mnds_pp_success "nvim" "done!"
