#!/bin/zsh

# Creating sb command for Sublime Text
sb () {
    if which subl &> /dev/null;
        then subl $@
    elif which subl3 > /dev/null;
        then subl3 $@
    else
        subl $@ 2>&1 > /dev/null &
    fi
}

# v command for vim
v() {
    if which vim &> /dev/null;
        then vim $@
    fi
}

# g command for git
if which git &> /dev/null;
    then alias g="git"
fi

# r command for rails
if which rails &> /dev/null;
    then alias r="rails"
fi

# Removing TeamSpeak 3 Client Polution
ts3 () {
    nohup ts3client 2>&1 > /dev/null &
    exit 1
}

# Creating mkcd: mkdir and cd
mkcd () {
    mkdir -p "$@";
    cd "$@"
}

# Creating cdl: cd and ls
cdl () {
    if [ "$#" -eq "0" ];
        then
            cd "$HOME";
        else
            cd "$@";
    fi

    ls;
}


# cat aliases
catv () {
    cat $@ | view -
}


catl () {
    cat $@ | less
}

# Listing files
alias -g ls="ls -CF --color=auto"
alias -g lla="ls -alF"
alias -g lsa="ls -aF"

# Creating compacted cd ..
alias -g ..="cdl .."
alias -g ..2="cdl ../.."
alias -g ..3="cdl ../../.."
alias -g ..4="cdl ../../../.."
alias -g ..5="cdl ../../../../.."

# Reloading zshrc
alias -g reload="source ~/.zshrc"

# vim-like exit
alias -g :q="exit"

# valgrind alias
alias -g valleak="valgrind --tool=memcheck --leak-check=yes"
alias -g valleak-line="valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all"

# Resuming screen
alias -g sr="screen -r"

# zeus alias
alias -g z="zeus"

# atom alias
alias -g at="atom"

# prolog alias
alias -g prolog="rlwrap sicstus"
