#!/bin/bash

# Listing files
alias ls="ls -CF --color=auto"
alias lla="ls -alF | less"
alias lsa="ls -alF"

# Creating sb command for Sublime Text
sb () {
    if which subl &> /dev/null;
        then subl $@
    elif which subl3 > /dev/null;
        then subl3 $@
    else
        subl $@ 2>&1 > /dev/null &
    fi
}

# v command for vim
v() {
	if which vim &> /dev/null;
		then vim $@
	fi
}

# g command for git
if which git &> /dev/null;
    then alias g="git"
fi

# r command for rails
if which rails &> /dev/null;
    then alias r="rails"
fi

# Removing TeamSpeak 3 Client Polution
ts3 () {
    nohup ts3client 2>&1 > /dev/null &
    exit 1
}

# Creating mkcd: mkdir and cd
mkcd () {
    mkdir -p "$@";
    cd "$@"
}

# Creating cdl: cd and ls
cdl () {
    if [ "$#" -eq "0" ];
        then
            cd "$HOME";
        else
            cd "$@";
    fi

    ls;
}

# Creating compacted cd ..
alias ..="cdl .."
alias ..2="cdl ../.."
alias ..3="cdl ../../.."
alias ..4="cdl ../../../.."
alias ..5="cdl ../../../../.."

# Reloading bashrc
alias reload="source ~/.bashrc"

# vim-like exit
alias :q="exit"

# valgrind alias
alias valleak="valgrind --tool=memcheck --leak-check=yes"
alias valleak-line="valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all"
