#!/bin/bash

# Listing files
alias .="ls -alF ."
alias ls="ls -CF --color=auto"
alias lla="ls -alF | less"
alias lsa="ls -alF"

# Creating compacted cd ..
alias ..="cdl .."
alias ..2="cdl ../.."
alias ..3="cdl ../../.."
alias ..4="cdl ../../../.."
alias ..5="cdl ../../../../.."

# Reloading bashrc
alias reload="source ~/.bashrc"

# vim-like exit
alias :q="exit"
