#!/bin/bash

# Creating sb command for Sublime Text
sb () {
	subl $@ 2>&1 > /dev/null &
}


# Removing TeamSpeak 3 Client Polution
ts3 () {
	nohup ts3client 2>&1 > /dev/null &
	exit 1
}

# Preventing NetBeans from occupying the terminal
nb() {
	nohup netbeans 2>&1 /dev/null &
	exit 1
}

# Creating mkcd: mkdir and cd
mkcd () {
	mkdir -p "$@";
	cd "$@"
}

# Creating cdl: cd and ls
cdl () {
	if [ "$#" -eq "0" ];
		then
			cd "$HOME";
		else
			cd "$@";
	fi

	ls;
}