#!/bin/bash

# Creating sb command for Sublime Text
sb () {
	if which subl &> /dev/null;
		then subl $@
	elif which subl3 > /dev/null;
		then subl3 $@
	else
		subl $@ 2>&1 > /dev/null &
	fi
}


# Removing TeamSpeak 3 Client Polution
ts3 () {
	nohup ts3client 2>&1 > /dev/null &
	exit 1
}

# Creating mkcd: mkdir and cd
mkcd () {
	mkdir -p "$@";
	cd "$@"
}

# Creating cdl: cd and ls
cdl () {
	if [ "$#" -eq "0" ];
		then
			cd "$HOME";
		else
			cd "$@";
	fi

	ls;
}
