#!/bin/bash

FRM_LOCAL="${HOME}/local"

export FRM_BIN="$FRM_LOCAL/bin"
export FRM_BASH="$FRM_LOCAL/bash"
export FRM_SCRIPTS="$FRM_LOCAL/scripts"


# Awesome ps1 prompt
source $FRM_BASH/setup_ps1
export PROMPT_COMMAND=setup_ps1
